format = """
[](#09f7a0)\
$username\
[](bg:#e95678 fg:#09f7a0)\
$directory\
[](fg:#e95678 bg:#f09483)\
$git_branch\
$git_status\
[](fg:#f09483 bg:#6bdfe9)\
$nodejs\
$rust\
[](fg:#6bdfe9 bg:#25b0bc)\
$time\
[ ](fg:#25b0bc)\
"""

# Disable the blank line at the start of the prompt
# add_newline = false

# You can also replace your username with a neat symbol like  to save some space
[username]
show_always = true
style_user = "fg:#1c1e26 bg:#09f7a0"
style_root = "fg:#1c1e26 bg:#09f7a0"
format = '[$user ]($style)'

[directory]
style = "fg:#1c1e26 bg:#e95678"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "

[git_branch]
symbol = ""
style = "fg:#1c1e26 bg:#f09483"
format = '[[ $symbol $branch ](fg:#1c1e26 bg:#f09483)]($style)'

[git_status]
style = "fg:#1c1e26 bg:#f09483"
format = '[[($all_status$ahead_behind )](fg:#1c1e26 bg:#f09483)]($style)'

[nodejs]
symbol = ""
style = "fg:#1c1e26 bg:#6bdfe9"
format = '[[ $symbol ($version) ](fg:#1c1e26 bg:#6bdfe9)]($style)'

[rust]
symbol = ""
style = "fg:#1c1e26 bg:#6bdfe9"
format = '[[ $symbol ($version) ](fg:#1c1e26 bg:#6bdfe9)]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "fg:#1c1e26 bg:#25b0bc"
format = '[[  $time ](fg:#1c1e26 bg:#25b0bc)]($style)'
